# Generated by Django 4.0.2 on 2022-02-04 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=240)),
                ('Emp_id', models.CharField(max_length=240)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=12)),
                ('Branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.branch')),
            ],
        ),
    ]
