# Generated by Django 4.0.2 on 2022-02-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_branch_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch_department',
            old_name='Branch_id',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='branch_manager',
            old_name='Branch_id',
            new_name='Branch',
        ),
    ]
